# Generated by Django 4.1.4 on 2023-01-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_comment_listing_remove_comments_listing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='imgage',
            new_name='image',
        ),
    ]
